{
    "model":{
        "model_name": "mobilenet-ssd",
        "model": "models/mobilenet-ssd/FP32/mobilenet-ssd.xml",
        "weights": "models/mobilenet-ssd/FP32/mobilenet-ssd.bin"
      },
     "engine":{
       "config": "config/mobilenet-ssd_accuracy_checker.yml"

     },
     "compression": {
        "target_device": "CPU",
        "algorithms": [
            {
                "name": "DefaultQuantization",
                "preset": "performance",
                "params": {
                    "stat_subset_size": 10
                }
            }
        ]
    }
}

    
        
        
